# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

$script = <<SCRIPT
#!/bin/bash

apt-get -y install git tidy
git clone https://github.com/fletcher/MultiMarkdown-4.git
cd MultiMarkdown-4
git checkout 4.6
git submodule init
git submodule update
make
cp multimarkdown /vagrant/
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "ubuntu/trusty64"

  config.vm.provision "shell", inline: $script

end
